import {describe,it,expect} from 'vitest';
import {bindClosingInstruction,verifyInstructionAtExecution,reconcileSettlementEvidence,type ClosingInstruction} from '../lib/closing-instruction-integrity';
const base:ClosingInstruction={dealId:'d1',workspaceId:'w1',stateVersion:7,counterpartyId:'cp1',counterpartyLegalName:'Seller Ltd',mandateId:'m1',rail:'WIRE',destination:'acct-001',beneficiaryName:'Seller Ltd',bankName:'Bank A',sourcePrincipalId:'p1',sourceChannel:'verified-portal',sourceChannelVerified:true,authorityVerified:true,independentlyVerified:true,verifiedAt:'2026-08-14T20:00:00Z',expiresAt:'2026-08-15T20:00:00Z'};
describe('closing instruction integrity',()=>{
 it('rejects last-minute beneficiary destination substitution',()=>{const b=bindClosingInstruction(base,new Date('2026-08-14T21:00:00Z'));const r=verifyInstructionAtExecution(b,{...base,destination:'acct-attacker'},new Date('2026-08-14T21:01:00Z'));expect(r.pass).toBe(false);expect(r.reasons).toContain('CLOSING_INSTRUCTION_SUBSTITUTED');});
 it('rejects counterparty or mandate substitution',()=>{const b=bindClosingInstruction(base,new Date('2026-08-14T21:00:00Z'));expect(verifyInstructionAtExecution(b,{...base,counterpartyId:'cp2'},new Date('2026-08-14T21:01:00Z')).reasons).toContain('COUNTERPARTY_IDENTITY_CHANGED');expect(verifyInstructionAtExecution(b,{...base,mandateId:'m2'},new Date('2026-08-14T21:01:00Z')).reasons).toContain('MANDATE_CHANGED');});
 it('requires trusted provenance and independent verification',()=>{expect(()=>bindClosingInstruction({...base,sourceChannelVerified:false},new Date('2026-08-14T21:00:00Z'))).toThrow();expect(()=>bindClosingInstruction({...base,independentlyVerified:false},new Date('2026-08-14T21:00:00Z'))).toThrow();});
 it('routes conflicting provider evidence to reconciliation',()=>{const b=bindClosingInstruction(base,new Date('2026-08-14T21:00:00Z'));const e={provider:'bank-a',dealId:'d1',workspaceId:'w1',instructionDigest:b.instructionDigest,transactionRef:'tx1',status:'SETTLED' as const,amount:'100',currencyOrAsset:'USD',verified:true};const r=reconcileSettlementEvidence([e,{...e,provider:'bank-b',status:'REVERSED'}],b);expect(r.pass).toBe(false);expect(r.state).toBe('RECONCILIATION_REQUIRED');});
 it('binds crypto destination changes too',()=>{const x={...base,rail:'XRP' as const,destination:'rGood',memoOrTag:'123'};const b=bindClosingInstruction(x,new Date('2026-08-14T21:00:00Z'));expect(verifyInstructionAtExecution(b,{...x,destination:'rBad'},new Date('2026-08-14T21:01:00Z')).pass).toBe(false);});
});
