import {describe,it,expect} from 'vitest'; import {createControlState,ingestDealEvent,replayDealEvents,type AuthoritativeDealEvent} from './deal-event-control-tower'; import type {AtlasDeal} from './types';
const deal:AtlasDeal={id:'d',organizationId:'o',workspaceId:'w',createdBy:'u',title:'deal',commodity:'gold',stage:'DD',participants:[],evidence:[],requirements:[],assumptions:[],createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
const ev=(x:Partial<AuthoritativeDealEvent>):AuthoritativeDealEvent=>({id:'e1',dealId:'d',organizationId:'o',workspaceId:'w',type:'TERMS_CHANGED',occurredAt:'2026-01-02T00:00:00Z',receivedAt:'2026-01-02T00:00:01Z',effectiveAt:'2026-01-02T00:00:00Z',payload:{quantity:10},idempotencyKey:'k1',source:'counterparty-verified',sourceAuthority:80,baseVersion:1,...x});
describe('event driven deal control tower',()=>{
 it('deduplicates retries',()=>{const s=createControlState(deal);expect(ingestDealEvent(s,ev({})).disposition).toBe('ACCEPT');expect(ingestDealEvent(s,ev({id:'retry'})).disposition).toBe('DUPLICATE');});
 it('quarantines cross-workspace events',()=>{const s=createControlState(deal);expect(ingestDealEvent(s,ev({workspaceId:'evil'})).disposition).toBe('QUARANTINE');});
 it('does not blindly apply stale version events',()=>{const s=createControlState(deal);ingestDealEvent(s,ev({}));const r=ingestDealEvent(s,ev({id:'e2',idempotencyKey:'k2',baseVersion:1,payload:{quantity:99}}));expect(r.disposition).toBe('LATE');expect(s.deal.quantity).toBe(10);});
 it('reconciles contradictory authoritative settlement events',()=>{const s=createControlState(deal);ingestDealEvent(s,ev({type:'SETTLEMENT_CONFIRMED',id:'a',idempotencyKey:'a'}));expect(ingestDealEvent(s,ev({type:'SETTLEMENT_REJECTED',id:'b',idempotencyKey:'b'})).disposition).toBe('RECONCILE');});
 it('replays deterministically regardless of input order',()=>{const a=ev({id:'a',idempotencyKey:'a',effectiveAt:'2026-01-02T00:00:00Z',payload:{quantity:10}}),b=ev({id:'b',idempotencyKey:'b',effectiveAt:'2026-01-03T00:00:00Z',baseVersion:2,payload:{quantity:20}});expect(replayDealEvents(deal,[b,a]).deal.quantity).toBe(replayDealEvents(deal,[a,b]).deal.quantity);});
});
