export type Rail="ACH"|"WIRE"|"CARD";
export type MoneyState="INITIATED"|"SETTLED"|"RETURNED"|"REVERSED"|"DISPUTED"|"REFUNDED";
export type FinancialEvent={eventId:string;paymentId:string;invoiceId:string;organizationId:string;workspaceId:string;rail:Rail;state:MoneyState;amountMinor:bigint;providerReference:string;occurredAt:string;originalEventId?:string};
const transitions:Record<MoneyState,MoneyState[]>={INITIATED:["SETTLED","RETURNED","REVERSED"],SETTLED:["RETURNED","REVERSED","DISPUTED","REFUNDED"],RETURNED:[],REVERSED:[],DISPUTED:["SETTLED","REVERSED","REFUNDED"],REFUNDED:[]};
export function validateTransition(from:MoneyState,to:MoneyState){return {ok:transitions[from].includes(to),from,to};}
export function financialAvailability(state:MoneyState){return {cashAvailable:state==="SETTLED",revenueEarned:false,treasuryAuthorized:false};}
export function validateExceptionEvent(e:FinancialEvent,prior?:FinancialEvent){const errors:string[]=[];if(!e.eventId||!e.paymentId||!e.invoiceId||!e.organizationId||!e.workspaceId||!e.providerReference)errors.push("MISSING_IDENTITY");if(e.amountMinor<=0n)errors.push("NON_POSITIVE_AMOUNT");if(prior){if(prior.organizationId!==e.organizationId||prior.workspaceId!==e.workspaceId||prior.paymentId!==e.paymentId||prior.invoiceId!==e.invoiceId)errors.push("SCOPE_OR_PAYMENT_MISMATCH");if(!validateTransition(prior.state,e.state).ok)errors.push("ILLEGAL_STATE_TRANSITION");if(["RETURNED","REVERSED","DISPUTED","REFUNDED"].includes(e.state)&&e.originalEventId!==prior.eventId)errors.push("MISSING_ORIGINAL_EVENT_LINK");}return {ok:errors.length===0,errors};}
export function reconcileSettlement(expectedMinor:bigint,events:FinancialEvent[]){let settled=0n;for(const e of events){if(e.state==="SETTLED")settled+=e.amountMinor;if(["RETURNED","REVERSED","REFUNDED"].includes(e.state))settled-=e.amountMinor;}return {netSettledMinor:settled,deltaMinor:settled-expectedMinor,ok:settled===expectedMinor};}
export function detectProviderReferenceReuse(events:FinancialEvent[]){const seen=new Map<string,string>();const conflicts:string[]=[];for(const e of events){const prior=seen.get(e.providerReference);if(prior&&prior!==e.paymentId)conflicts.push(e.providerReference);else seen.set(e.providerReference,e.paymentId);}return {ok:conflicts.length===0,conflicts};}
